### ISSUE TITLE
Set up Django Project: Manager Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six_day-plan#2]
As a **Project Manager** I can **check all tasks** so that **the project will be submitted on time **.

# ACCEPTANCE CRITERIA

User stories and tasks should be added to backlog to keep the project on track.

# TASKS

- [x] Create a project/ new repository
- [x] Enter User Stories
- [x] Add User stories and create workspace (User stories are pulled automatically)

- [x] _**AT THE TERMINAL**_
- [x] Install Django package <**pip3 install Django~=4.2.1**>
- [x] Install requirements <**pip3 freeze --local > requirements.txt**>
- [x] Set up project <**django-admin startproject <project name  .**> **Keep dot in the end**
- [x] Start server <**python3 manage.py runserver**>
- [x] Open Browser and copy the hostname <**'8000-felipeseibe-djangoproje-7v6o2laivmz.ws-eu107.gitpod.io'**>
- [x] Open main file/settings/ ALLOWED_HOST [ <**paste it**>]
- [x] **_CREATE AN APP_**
- [x] Create an app <**python3 manage.py startapp <app's name>**>
- [x] Create a view function & URL pattern

- **Settings.py/Installed apps:**

**'app's name',**

- **Views**

from django.http import HttpResponse

def my_blog(request):
       return HttpResponse("Hello, Blog!")  **DONT FORGET IDENTATION**

- **URLs**

from blog.views import my_blog
path('App/', variable's name, name='app's name'),

- [x] Run server to test

- [ ] _**HEROKU**_
- [x] Create a Heroku app/give an unique name.
- [x] Settings/Config vars/ <**DISABLE_COLLECTSTATIC**> Key: **1** (_prevents Heroku from uploading static files, such as CSS and JS_)
- [x] Install a production-ready webserver for Heroku <**pip3 install gunicorn~=20.1**>
- [x] Add **gunicorn~=20.1** to the requirements.txt file <**pip3 freeze --local > requirements.txt**>
- [x] Create a **Procfile** file at the root directory
- [x] In the Procfile <**web: gunicorn my_project.wsgi**>
- [x] At the main project open **Settings** and replace DEBUG=True with **DEBUG=False.**
- [x] Still in the Settings add <**'.herokuapp.com'**> to ALLOWED_HOSTS.
- [x] Deploy <tab> on Heroku / connect to GitHub / Search for your project / Deploy main branch
- [x] Open app
- [x] Resources / Eco Dynos - _lighter version._
- [x] Check if there is any add on attached. Delete it/them. Can cause extra costs!

- [x] _**IMAGES STATIC AND POST**_
- [x] Install <**pip3 install whitenoise~=6.5.0**> Whitenoise to host the static files
- [x] <pip3 freeze --local > requirements.txt>
- [x] Git add, git commit and git push
- [x] Deploy Heroku
- [ ] Install <pip3 install cloudinary...> Cloudinary stores images.

- [x] _**DATA BASE ELEPHANTSQL**_
- [x] Create a Page Diagram - **ERDs** (Entity Relationship Diagrams)
- [x] Create a database (**ElephantSQL**)
- [x] Check **STATS** tab PostgreSQL is 12 or higher
- [x] Copy URL displayed at details
- [x] Switch DEBUG = True
- [x] Create a env.py file <**touch env.py**> at terminal
- [x] Double check if env.py is present at **Gitignore file**
- [x] env.py file add: import os
os.environ.setdefault(
    "DATABASE_URL",  "copied database URL")
- [x] Connecting to your PostgreSQL database:
- [x] **pip3 install dj-database-url~=0.5 psycopg2~=2.9**
- [x] **pip3 freeze --local > requirements.txt**

- **psycopg2**: driver for interacting with PostgreSQL databases using Python
- **dj-database-url**: utility to connect Django to a database using a URL

- [x] Import the appropriate packages to Settings.py

- import os
import dj_database_url
if os.path.isfile('env.py'):
    import env              **DONT FORGET IDENTATION**

- [x] **import os
import dj_database_url
if os.path.isfile('env.py'):
     import env** **_Add a tab to give space_**
- [x] Comment (**#**) local sqlite3 DATABASES (below)
- [x] add variable <**DATABASES = {
    'default': dj_database_url.parse(os.environ.get("DATABASE_URL"))
}**>

- [ ] **_CREATE DATABASE TABLES WITH MIGRATE_**
- [x] Migrate <**python3 manage.py makemigrations --dry-run**>
- [x] Migrate <**python3 manage.py showmigrations**>
- [x] Migrate <**python3 manage.py migrate --plan**>
- [x] Migrate <**python3 manage.py migrate**>
- [x] Superuser <**python3 manage.py createsuperuser**>
- [x] Check Database / BROWSER, Table queries, auth_user (public) and then Execute
- [x] Return **DEBUG** to **False**
- [x] Git add, commit and push <**...-m "Deployment settings"**> 

- [ ] **_DEPLOY PROJECT_** _**CONNECT TO DATABASE**_
- [x] Deploy tab at Heroku and Deploy branch manually
- [x] Connect Heroku to the PostgreSQL database
- [x] Check reveal conf vars in the settings
- [x] If Heroku DATABASE_URL is present delete it and replace it by ElephantSQL URL.
- [x] Open app

- [x] **_SET UP NEW SECRET_KEY_**
- [x] Generate new secret key / open **env.py**
- [x] **os.environ.setdefault("SECRET_KEY", "<your_choice_of_secret_key>")**
- [x] At settings.py **<SECRET_KEY = os.environ.get("SECRET_KEY")>**
- [x] set on Heroku as a **Config Var named SECRET_KEY** + **secret key**

- [x] **_CREATE A POST MODEL CODE_**
- [x] Change **DEBUG** to True
- [x] POST App/models.py
- [x] Add import <**from django.contrib.auth.models import User**>
- [x] Create a class <**class Post(models.Model):**>
- [x] Enter attributes: tittle, slug, author...

- [x] Convert Python class into instructions : <**python3 manage.py makemigrations Post App'name**>
- [x] Create table in the database <**python3 manage.py migrate blog**>
- [x] Open Post app/ admin.py and paste:

- from .models import Post

- [x] Open project file/ settings/ above database paste:

- CSRF_TRUSTED_ORIGINS = [
    "https://*.codeanyapp.com",    (**Code Anywhere**)
    "https://*.gitpod.io",                 (**Gitpod**)
    "https://*.herokuapp.com"
]

- [x] Run server
- [x] Open admin/ Check if there is a new field called Post
- [x] Return DEBUG to False
- [x] Git add, commit and push
- [x] Manual Deploy
- [x] Open App/admin

- **Every time you change or add a field in the model you should:**

- [x] <**python3 manage.py makemigrations --dry-run**>  (To visualize)
- [x] <**python3 manage.py makemigrations**>  (To create local file)
- [x] <**python3 manage.py migrate**> (To update the database)

- [x] _**ADD USER AND POSTS**_
- [x] Log in into **admin** dashboard
- [x] Enter: username/password/confirm password and save

- [x] ADD METHODS TO DJANGO MODELS
- [x] ADD THE METHODS BELLOW THE CLASSES

- **class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"** 

- [x] **_CHANGE MODEL FIELDS DEBBUGING_**
- [x] <**python3 manage.py migrate (App's name) zero**>   _This reset the migration / Assure to re-add them in the admin panel._
- [x] Delete the offending migration files
- [x]  <**python3 manage.py makemigrations**>  (To create local file)
- [x] <**python3 manage.py migrate**> (To update the database)

- [ ] **_DJANGO VIEWS_**
- [ ] Create a **urls.py** file in the directory of your app
- [ ] Delete the _views import related to this app on the urls.py/main
- [ ] Be sure u have include add after path like this: (**from django.urls import path, _include_**)
- [ ] APP/ urlpattern, replace it by: <**path("", include("blog.urls"), name="blog-urls"),**>
- [ ] Create a template directory: <**mkdir -p blog/templates/blog**>

- [ ] INSTALL SUMMERNOTE

- Django_summernote is a Django app with urls.py, admin.py and migrations files not a Python package. that is why:

- The INSTALLED_APPS in settings.py,.

-     The urlpatterns path in urls.py.

-     python3 manage.py migrations.

are necessary on top of the requirements.txt inclusion.

- [ ] <**pip3 install django-summernote~=0.8.20.0**>
- [ ] <pip3 freeze --local > requirements.txt>
- [ ] INSTALLED APPS: <**'django_summernote',**>
- [ ] Main urls.py/ urlspatterns: <**path('summernote/', include('django_summernote.urls')),**>
- [ ] As we will add more paths in the future, now is an excellent time to order the string paths alphabetically, with the empty string path last. 
- [ ] Apps/admin.py:
- [ ]  <**from** django_summernote.admin **import** SummernoteModelAdmin>
- [ ] Add the decorator and PostAdmin class below the import:

@admin.register(Post)
class PostAdmin(SummernoteModelAdmin):

    list_display = ('title', 'slug', 'status')
    search_fields = ['title']
    list_filter = ('status',)
    prepopulated_fields = {'slug': ('title',)}
    summernote_fields = ('content',)    **IDENTETION**

- [ ] Delete the existing Post model registration. (**admin.site.register(Post**))
- [ ] <**python3 manage.py migrate**>
- [ ] Run server
