### ISSUE TITLE
Add Answers: User Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six_day-plan#4]
As a **Site user** I can **I can edit into my Health form questionnaire** so that **the Personal Trainer has the information needed to build an exercise program **.

# ACCEPTANCE CRITERIA

Questionnaire form allows users to provide answers.

# TASKS

- [ ] Provide yes or no fields.
- [ ] Create boxes for text.
- [ ] Create a submit button.

**Comment by VidyaYadavv1519** [comment]
Hiii, i want to do this issue,
can you assign me ??
