### ISSUE TITLE
Account registration: User Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six_day-plan#6]
As a **Site user** I can **register an account** so that **I can log in into my personal space**.

# ACCEPTANCE CRITERIA

User provide email and password and access to personal space is granted.

# TASKS

- [ ] Create a sign up button.
- [ ] Create a sign in button.
- [ ] Send a confirmation email to the user with log in credentials.
