### ISSUE TITLE
Select location: User Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six_day-plan#7]
As a **Potential gym member** I can **Select the most convenient Gym venue** so that **I can find the closest gym from my work or home**.

# ACCEPTANCE CRITERIA

List of clubs are available.

# TASKS

- [ ] Create list of clubs.
- [ ] Provide respective addresses.
- [ ] List them in the Google Maps.
