### ISSUE TITLE
Set up Django Project: Manager Story 1: Manager Story

### ISSUE THREAD

**Issue by FelipeSeiberlich** [FelipeSeiberlich/six_day-plan#8]
As a Project Manager I can check all tasks so that **the project will be submitted on time **.

# ACCEPTANCE CRITERIA

User stories and tasks should be added to backlog to keep the project on track.

# TASKS

- [x] **_CREATE TEMPLATES_**
- [x] Main/Settings: Build path inside the project: <**TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')**>
- [x] Add your newly created TEMPLATES_DIR constant to the list of 'DIRS': <'DIRS': [**TEMPLATES_DIR**],>
- [x] Add a new top-level templates directory
- [x] Add a base.html file to the new template directory
- [x] Add code to base.html <[code linked here](https://github.com/Code-Institute-Solutions/blog/blob/main/08_templates/01_base_template/base.html)>
- [x] Add index.html to templates/blog
- [x] Add [code linked here](https://github.com/Code-Institute-Solutions/blog/blob/main/08_templates/01_base_template/index.html) to the index.html
- [x] Open the blog/views.py file 

_replace:_
template_name = "post_list.html"

_for:_
template_name = "blog/index.html"
paginate_by = 6

- [x] Delete (post_list.html template)
- [x] Run server
- [x] Create a top-level static/css directory
- [x] create a style.css file
- [x] [CSS code linked here](https://github.com/Code-Institute-Solutions/blog/blob/main/08_templates/01_base_template/style.css) to style.css
- [x] main/settings under the static file paste: <**STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]**>
- [x] Open the base.html file and past on the top of the page: {% load static %}
- [x] In the same file paste this under the bootstrap section: 
Custom CSS - comment this!
link rel="stylesheet" href="{% static 'css/style.css' %}"
- [x] Refresh Homepage

- [x] CREATE BLOCKS
- [x] LIKE EXAMPLE:
{% block content %}
    
{% endblock content %}

- [x] All the block and endblock tags do is tell Django's templating engine that a child template may fill them with content.
